# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-16 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storeId', models.CharField(max_length=256)),
                ('room_id', models.CharField(max_length=256)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('queue_id', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('beatsPerMinute', models.IntegerField(default=0)),
                ('playCount', models.IntegerField(default=0)),
                ('storeId', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('albumArtRef', models.CharField(max_length=1024)),
                ('artistId', models.CharField(max_length=256)),
                ('creationTimestamp', models.CharField(max_length=256)),
                ('album', models.CharField(max_length=256)),
                ('recentTimestamp', models.CharField(max_length=256)),
                ('artist', models.CharField(max_length=256)),
                ('nid', models.CharField(max_length=256)),
                ('estimatedSize', models.CharField(max_length=256)),
                ('albumId', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('artistArtRef', models.CharField(max_length=1024)),
                ('kind', models.CharField(max_length=256)),
                ('lastModifiedTimestamp', models.CharField(max_length=256)),
                ('durationMillis', models.CharField(max_length=256)),
            ],
        ),
    ]
